spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  security:
    jwt:
      tokenSecret: ${JWT_SECRET_KEY}
    cors:
      allowedOrigins: http://${SERVER_IP}
    oauth2:
      authorizedRedirectUris:
        - http://${SERVER_IP}/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect
  front-url: http://${SERVER_IP}