spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diet_detective
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0

app:
  security:
    jwt:
      tokenSecret: ${JWT_SECRET_KEY}
      tokenExpirationSeconds: 1209600 # 14 days
    cors:
      allowedOrigins: \*
    oauth2:
      # After successfully authenticating with the OAuth2 Provider,
      # we'll be generating an auth token for the user and sending the token to the
      # redirectUri mentioned by the client in the /oauth2/authorize request.
      # We're not using cookies because they won't work well in mobile clients.
      authorizedRedirectUris:
        - http://localhost:3000/oauth2/redirect
        - myandroidapp://oauth2/redirect
        - myiosapp://oauth2/redirect

  front-url: http://localhost:3000
server:
  error:
    include-message: always